-- =====================================================================
-- GuardianAI | File 03c: Load PAYMENTS + INVENTORY (large)
-- Reuses the GUARDIANAI_CSV file format. Load AFTER orders/products exist.
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

TRUNCATE TABLE PAYMENTS;
TRUNCATE TABLE INVENTORY;

CREATE OR REPLACE FILE FORMAT GUARDIANAI_CSV
    TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null') EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE;

-- OPTION A: Snowsight UI upload (fastest for trial accounts)
--   Data > PAYMENTS  > Load Data > payments_large.csv  > format GUARDIANAI_CSV
--   Data > INVENTORY > Load Data > inventory_large.csv > format GUARDIANAI_CSV

-- OPTION B: staged PUT + COPY
-- CREATE OR REPLACE STAGE GUARDIANAI_STAGE FILE_FORMAT = GUARDIANAI_CSV;


COPY INTO PAYMENTS  FROM @GUARDIANAI_STAGE/PAYMENTS.csv
    FILE_FORMAT = (FORMAT_NAME = GUARDIANAI_CSV) ON_ERROR = 'CONTINUE';
COPY INTO INVENTORY FROM @GUARDIANAI_STAGE/INVENTORY.csv
    FILE_FORMAT = (FORMAT_NAME = GUARDIANAI_CSV) ON_ERROR = 'CONTINUE';

SELECT 'PAYMENTS' AS tbl, COUNT(*) AS rows1 FROM PAYMENTS
UNION ALL SELECT 'INVENTORY', COUNT(*) FROM INVENTORY;
