-- =====================================================================
-- GuardianAI | File 04: Data Observer Agent - detect ALL 5 tables
-- =====================================================================
-- Deterministic SQL detection; writes one row per issue into DQ_ISSUES.
-- Principle: SQL detects (reliable & explainable). Cortex reasons later.
-- TRUNCATEs DQ_ISSUES once, then runs all 27 checks (15 base + 12 new).
--
-- Penalty/severity convention: CRITICAL=20 | HIGH=10 | MEDIUM=7 | LOW=3
-- (PENALTY column is legacy; the volume-aware score in file 05 uses
--  SEVERITY + AFFECTED_ROWS, not this flat number.)
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

TRUNCATE TABLE DQ_ISSUES;

-- =====================================================================
-- CUSTOMERS
-- =====================================================================
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','MISSING_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS WHERE EMAIL IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','INVALID_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS
WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','DUPLICATE_CUSTOMER_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT CUSTOMER_ID,COUNT(*) cnt FROM CUSTOMERS WHERE CUSTOMER_ID IS NOT NULL GROUP BY CUSTOMER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','MISSING_CUSTOMER_ID','CRITICAL',20,COUNT(*) FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','STATE','MISSING_STATE','LOW',3,COUNT(*) FROM CUSTOMERS WHERE STATE IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','PHONE','INVALID_PHONE','MEDIUM',7,COUNT(*) FROM CUSTOMERS
WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE,'^[0-9]{10}$') HAVING COUNT(*)>0;

-- =====================================================================
-- ORDERS
-- =====================================================================
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_DATE','FUTURE_ORDER_DATE','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_DATE(ORDER_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','MISSING_ORDER_CUSTOMER','HIGH',10,COUNT(*) FROM ORDERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','ORPHAN_ORDER','CRITICAL',20,COUNT(*) FROM ORDERS o
WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_AMOUNT','NEGATIVE_ORDER_AMOUNT','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_NUMBER(ORDER_AMOUNT)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_ID','DUPLICATE_ORDER_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT ORDER_ID,COUNT(*) cnt FROM ORDERS GROUP BY ORDER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;

-- =====================================================================
-- PRODUCTS
-- =====================================================================
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','PRICE','NEGATIVE_PRICE','MEDIUM',7,COUNT(*) FROM PRODUCTS WHERE TRY_TO_NUMBER(PRICE)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','CATEGORY','MISSING_CATEGORY','LOW',3,COUNT(*) FROM PRODUCTS WHERE CATEGORY IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','PRODUCT_ID','DUPLICATE_PRODUCT_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT PRODUCT_ID,COUNT(*) cnt FROM PRODUCTS GROUP BY PRODUCT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','ACTIVE_FLAG','INVALID_ACTIVE_FLAG','MEDIUM',7,COUNT(*) FROM PRODUCTS
WHERE ACTIVE_FLAG NOT IN ('Y','N') OR ACTIVE_FLAG IS NULL HAVING COUNT(*)>0;

-- =====================================================================
-- PAYMENTS  (within-table + CROSS-TABLE checks)
-- =====================================================================
-- De-duplicated order amounts for the mismatch check (ORDERS may have dup ids)
CREATE OR REPLACE TEMPORARY TABLE _ORD_AMT AS
SELECT ORDER_ID, MIN(TRY_TO_NUMBER(ORDER_AMOUNT)) AS ORDER_AMOUNT
FROM ORDERS WHERE ORDER_ID IS NOT NULL GROUP BY ORDER_ID;

INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_ID','DUPLICATE_PAYMENT_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT PAYMENT_ID,COUNT(*) cnt FROM PAYMENTS GROUP BY PAYMENT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','MISSING_ORDER_REF','HIGH',10,COUNT(*) FROM PAYMENTS WHERE ORDER_ID IS NULL HAVING COUNT(*)>0;
-- CROSS-TABLE: orphan payment (order_id not in ORDERS)
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','ORPHAN_PAYMENT','CRITICAL',20,COUNT(*) FROM PAYMENTS p
WHERE p.ORDER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID) HAVING COUNT(*)>0;
-- CROSS-TABLE: payment amount != matching order amount (business-logic check)
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','PAYMENT_AMOUNT_MISMATCH','HIGH',10,COUNT(*)
FROM PAYMENTS p JOIN _ORD_AMT o ON o.ORDER_ID=p.ORDER_ID
WHERE TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL AND o.ORDER_AMOUNT IS NOT NULL
  AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT))<>ABS(o.ORDER_AMOUNT) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','NEGATIVE_PAYMENT_AMOUNT','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_NUMBER(PAYMENT_AMOUNT)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_DATE','FUTURE_PAYMENT_DATE','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_DATE(PAYMENT_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_METHOD','INVALID_PAYMENT_METHOD','MEDIUM',7,COUNT(*) FROM PAYMENTS
WHERE PAYMENT_METHOD IS NULL OR PAYMENT_METHOD NOT IN ('CARD','UPI','NETBANKING','WALLET','COD') HAVING COUNT(*)>0;

-- =====================================================================
-- INVENTORY  (within-table + CROSS-TABLE checks)
-- =====================================================================
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','INVENTORY_ID','DUPLICATE_INVENTORY_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT INVENTORY_ID,COUNT(*) cnt FROM INVENTORY GROUP BY INVENTORY_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','MISSING_PRODUCT_REF','HIGH',10,COUNT(*) FROM INVENTORY WHERE PRODUCT_ID IS NULL HAVING COUNT(*)>0;
-- CROSS-TABLE: orphan inventory (product_id not in PRODUCTS)
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','ORPHAN_INVENTORY','CRITICAL',20,COUNT(*) FROM INVENTORY i
WHERE i.PRODUCT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID=i.PRODUCT_ID) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','STOCK_QTY','NEGATIVE_STOCK','MEDIUM',7,COUNT(*) FROM INVENTORY WHERE TRY_TO_NUMBER(STOCK_QTY)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','WAREHOUSE','INVALID_WAREHOUSE','LOW',3,COUNT(*) FROM INVENTORY
WHERE WAREHOUSE IS NULL OR WAREHOUSE NOT IN ('WH-MUM','WH-DEL','WH-BLR','WH-KOL','WH-CHN','WH-HYD') HAVING COUNT(*)>0;

-- =====================================================================
-- Review everything the Observer Agent found (all 5 tables)
-- =====================================================================
SELECT TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS, STATUS
FROM DQ_ISSUES
ORDER BY TABLE_NAME,
         CASE SEVERITY WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2
                       WHEN 'MEDIUM' THEN 3 ELSE 4 END;
