-- =====================================================================
-- GuardianAI | File 04: Data Observer Agent - deterministic SQL checks
-- Detects issues and writes one row per issue into DQ_ISSUES.
-- Principle: SQL does detection (reliable & explainable). Cortex comes later.
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

-- Start clean each scan
TRUNCATE TABLE DQ_ISSUES;

-- Penalty/severity convention (matches strategy brief Section 12):
--   CRITICAL = 20 | HIGH = 10 | MEDIUM = 7 | LOW = 3

-- =====================================================================
-- CUSTOMERS CHECKS
-- =====================================================================

-- Missing email (mandatory field) -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','MISSING_EMAIL','HIGH',10, COUNT(*)
FROM CUSTOMERS WHERE EMAIL IS NULL
HAVING COUNT(*) > 0;

-- Invalid email format -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','INVALID_EMAIL','HIGH',10, COUNT(*)
FROM CUSTOMERS
WHERE EMAIL IS NOT NULL
  AND NOT REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
HAVING COUNT(*) > 0;

-- Duplicate customer IDs -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','DUPLICATE_CUSTOMER_ID','CRITICAL',20,
       SUM(cnt) FROM (
    SELECT CUSTOMER_ID, COUNT(*) cnt
    FROM CUSTOMERS WHERE CUSTOMER_ID IS NOT NULL
    GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1
) d
HAVING SUM(cnt) > 0;

-- Missing customer ID (primary key null) -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','MISSING_CUSTOMER_ID','CRITICAL',20, COUNT(*)
FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL
HAVING COUNT(*) > 0;

-- Missing state (optional field) -> LOW
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','STATE','MISSING_STATE','LOW',3, COUNT(*)
FROM CUSTOMERS WHERE STATE IS NULL
HAVING COUNT(*) > 0;

-- Invalid phone (not 10 digits) -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'CUSTOMERS','PHONE','INVALID_PHONE','MEDIUM',7, COUNT(*)
FROM CUSTOMERS
WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE, '^[0-9]{10}$')
HAVING COUNT(*) > 0;

-- =====================================================================
-- ORDERS CHECKS
-- =====================================================================

-- Future order date -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_DATE','FUTURE_ORDER_DATE','MEDIUM',7, COUNT(*)
FROM ORDERS
WHERE TRY_TO_DATE(ORDER_DATE) > CURRENT_DATE()
HAVING COUNT(*) > 0;

-- Missing customer id on order -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','MISSING_ORDER_CUSTOMER','HIGH',10, COUNT(*)
FROM ORDERS WHERE CUSTOMER_ID IS NULL
HAVING COUNT(*) > 0;

-- Orphan order (customer id not in CUSTOMERS) -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','ORPHAN_ORDER','CRITICAL',20, COUNT(*)
FROM ORDERS o
WHERE o.CUSTOMER_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID = o.CUSTOMER_ID)
HAVING COUNT(*) > 0;

-- Negative order amount -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_AMOUNT','NEGATIVE_ORDER_AMOUNT','MEDIUM',7, COUNT(*)
FROM ORDERS WHERE TRY_TO_NUMBER(ORDER_AMOUNT) < 0
HAVING COUNT(*) > 0;

-- Duplicate order IDs -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_ID','DUPLICATE_ORDER_ID','CRITICAL',20, SUM(cnt) FROM (
    SELECT ORDER_ID, COUNT(*) cnt FROM ORDERS
    GROUP BY ORDER_ID HAVING COUNT(*) > 1
) d
HAVING SUM(cnt) > 0;

-- =====================================================================
-- PRODUCTS CHECKS
-- =====================================================================

-- Negative price -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'PRODUCTS','PRICE','NEGATIVE_PRICE','MEDIUM',7, COUNT(*)
FROM PRODUCTS WHERE TRY_TO_NUMBER(PRICE) < 0
HAVING COUNT(*) > 0;

-- Missing category -> LOW
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'PRODUCTS','CATEGORY','MISSING_CATEGORY','LOW',3, COUNT(*)
FROM PRODUCTS WHERE CATEGORY IS NULL
HAVING COUNT(*) > 0;

-- Duplicate product IDs -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'PRODUCTS','PRODUCT_ID','DUPLICATE_PRODUCT_ID','CRITICAL',20, SUM(cnt) FROM (
    SELECT PRODUCT_ID, COUNT(*) cnt FROM PRODUCTS
    GROUP BY PRODUCT_ID HAVING COUNT(*) > 1
) d
HAVING SUM(cnt) > 0;

-- Invalid active flag (not Y/N) -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME, COLUMN_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS)
SELECT 'PRODUCTS','ACTIVE_FLAG','INVALID_ACTIVE_FLAG','MEDIUM',7, COUNT(*)
FROM PRODUCTS WHERE ACTIVE_FLAG NOT IN ('Y','N') OR ACTIVE_FLAG IS NULL
HAVING COUNT(*) > 0;

-- Review everything the Observer Agent found
SELECT TABLE_NAME, ISSUE_TYPE, SEVERITY, PENALTY, AFFECTED_ROWS, STATUS
FROM DQ_ISSUES
ORDER BY CASE SEVERITY WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2
                       WHEN 'MEDIUM' THEN 3 ELSE 4 END, TABLE_NAME;
