-- =====================================================================
-- GuardianAI | File 17: OBSERVER AGENT extension for PAYMENTS + INVENTORY
-- Adds within-table AND cross-table (referential + business-logic) checks.
-- Appends rows to the SAME DQ_ISSUES table, so scoring/remediation/app all
-- pick them up automatically.
--
-- IMPORTANT: run file 04 first (it TRUNCATEs DQ_ISSUES and loads the base 3
-- tables' issues). This file only INSERTs the 2 new tables' issues on top.
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

-- De-duplicated order amounts (ORDERS may contain duplicate order ids)
CREATE OR REPLACE TEMPORARY TABLE _ORD_AMT AS
SELECT ORDER_ID, MIN(TRY_TO_NUMBER(ORDER_AMOUNT)) AS ORDER_AMOUNT
FROM ORDERS WHERE ORDER_ID IS NOT NULL GROUP BY ORDER_ID;

-- =====================================================================
-- PAYMENTS CHECKS
-- =====================================================================

-- Duplicate payment id -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_ID','DUPLICATE_PAYMENT_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT PAYMENT_ID,COUNT(*) cnt FROM PAYMENTS GROUP BY PAYMENT_ID HAVING COUNT(*)>1) d
HAVING SUM(cnt)>0;

-- Missing order reference (null FK) -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','MISSING_ORDER_REF','HIGH',10,COUNT(*)
FROM PAYMENTS WHERE ORDER_ID IS NULL HAVING COUNT(*)>0;

-- CROSS-TABLE: orphan payment (order_id not in ORDERS) -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','ORPHAN_PAYMENT','CRITICAL',20,COUNT(*)
FROM PAYMENTS p
WHERE p.ORDER_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID = p.ORDER_ID)
HAVING COUNT(*)>0;

-- CROSS-TABLE: payment amount mismatch vs matching order -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','PAYMENT_AMOUNT_MISMATCH','HIGH',10,COUNT(*)
FROM PAYMENTS p
JOIN _ORD_AMT o ON o.ORDER_ID = p.ORDER_ID
WHERE TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL
  AND o.ORDER_AMOUNT IS NOT NULL
  AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT)) <> ABS(o.ORDER_AMOUNT)
HAVING COUNT(*)>0;

-- Negative payment amount -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','NEGATIVE_PAYMENT_AMOUNT','MEDIUM',7,COUNT(*)
FROM PAYMENTS WHERE TRY_TO_NUMBER(PAYMENT_AMOUNT)<0 HAVING COUNT(*)>0;

-- Future payment date -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_DATE','FUTURE_PAYMENT_DATE','MEDIUM',7,COUNT(*)
FROM PAYMENTS WHERE TRY_TO_DATE(PAYMENT_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;

-- Invalid payment method -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_METHOD','INVALID_PAYMENT_METHOD','MEDIUM',7,COUNT(*)
FROM PAYMENTS
WHERE PAYMENT_METHOD IS NULL
   OR PAYMENT_METHOD NOT IN ('CARD','UPI','NETBANKING','WALLET','COD')
HAVING COUNT(*)>0;

-- =====================================================================
-- INVENTORY CHECKS
-- =====================================================================

-- Duplicate inventory id -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','INVENTORY_ID','DUPLICATE_INVENTORY_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT INVENTORY_ID,COUNT(*) cnt FROM INVENTORY GROUP BY INVENTORY_ID HAVING COUNT(*)>1) d
HAVING SUM(cnt)>0;

-- Missing product reference (null FK) -> HIGH
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','MISSING_PRODUCT_REF','HIGH',10,COUNT(*)
FROM INVENTORY WHERE PRODUCT_ID IS NULL HAVING COUNT(*)>0;

-- CROSS-TABLE: orphan inventory (product_id not in PRODUCTS) -> CRITICAL
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','ORPHAN_INVENTORY','CRITICAL',20,COUNT(*)
FROM INVENTORY i
WHERE i.PRODUCT_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID = i.PRODUCT_ID)
HAVING COUNT(*)>0;

-- Negative stock -> MEDIUM
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','STOCK_QTY','NEGATIVE_STOCK','MEDIUM',7,COUNT(*)
FROM INVENTORY WHERE TRY_TO_NUMBER(STOCK_QTY)<0 HAVING COUNT(*)>0;

-- Invalid warehouse -> LOW
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','WAREHOUSE','INVALID_WAREHOUSE','LOW',3,COUNT(*)
FROM INVENTORY
WHERE WAREHOUSE IS NULL
   OR WAREHOUSE NOT IN ('WH-MUM','WH-DEL','WH-BLR','WH-KOL','WH-CHN','WH-HYD')
HAVING COUNT(*)>0;

-- Review the new tables' findings
SELECT TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS
FROM DQ_ISSUES
WHERE TABLE_NAME IN ('PAYMENTS','INVENTORY')
ORDER BY TABLE_NAME,
         CASE SEVERITY WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2
                       WHEN 'MEDIUM' THEN 3 ELSE 4 END;
