-- =====================================================================
-- GuardianAI | File 12: REMEDIATION AGENT
-- Builds one remediation plan row per open issue.
--   * FIX_SQL is deterministic (safe, auditable) - NOT AI generated.
--   * RECOMMENDED_ACTION is AI-narrated (Cortex) for the human reviewer.
--   * CONFIDENCE / RISK / REQUIRES_APPROVAL are policy-driven.
-- Principle: AI advises, SQL executes, a human approves. Nothing runs yet.
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

TRUNCATE TABLE DQ_REMEDIATION_PLAN;

-- ---------------------------------------------------------------------
-- Seed a plan row for every open issue, with deterministic fix strategy.
-- FIX_METHOD: AUTO_FIX (in-place value fix) | DEDUP | QUARANTINE
-- ---------------------------------------------------------------------
INSERT INTO DQ_REMEDIATION_PLAN
    (ISSUE_ID, TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS,
     FIX_METHOD, FIX_SQL, CONFIDENCE, RISK_LEVEL, REQUIRES_APPROVAL)
SELECT
    i.ISSUE_ID, i.TABLE_NAME, i.ISSUE_TYPE, i.SEVERITY, i.AFFECTED_ROWS,
    m.FIX_METHOD, m.FIX_SQL, m.CONFIDENCE, m.RISK_LEVEL, m.REQUIRES_APPROVAL
FROM DQ_ISSUES i
JOIN (
    SELECT 'MISSING_STATE' AS ISSUE_TYPE, 'AUTO_FIX' AS FIX_METHOD,
           'UPDATE CUSTOMERS SET STATE=''UNKNOWN'' WHERE STATE IS NULL' AS FIX_SQL,
           95 AS CONFIDENCE, 'LOW' AS RISK_LEVEL, FALSE AS REQUIRES_APPROVAL
    UNION ALL SELECT 'INVALID_PHONE','AUTO_FIX',
           'UPDATE CUSTOMERS SET PHONE=NULL WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE,''^[0-9]{10}$'')',
           90,'LOW',FALSE
    UNION ALL SELECT 'MISSING_CATEGORY','AUTO_FIX',
           'UPDATE PRODUCTS SET CATEGORY=''UNCATEGORIZED'' WHERE CATEGORY IS NULL',
           95,'LOW',FALSE
    UNION ALL SELECT 'INVALID_ACTIVE_FLAG','AUTO_FIX',
           'UPDATE PRODUCTS SET ACTIVE_FLAG=''N'' WHERE ACTIVE_FLAG NOT IN (''Y'',''N'') OR ACTIVE_FLAG IS NULL',
           85,'MEDIUM',FALSE
    UNION ALL SELECT 'NEGATIVE_PRICE','AUTO_FIX',
           'UPDATE PRODUCTS SET PRICE=ABS(TRY_TO_NUMBER(PRICE)) WHERE TRY_TO_NUMBER(PRICE)<0',
           80,'MEDIUM',TRUE
    UNION ALL SELECT 'NEGATIVE_ORDER_AMOUNT','AUTO_FIX',
           'UPDATE ORDERS SET ORDER_AMOUNT=ABS(TRY_TO_NUMBER(ORDER_AMOUNT)) WHERE TRY_TO_NUMBER(ORDER_AMOUNT)<0',
           80,'MEDIUM',TRUE
    UNION ALL SELECT 'FUTURE_ORDER_DATE','AUTO_FIX',
           'UPDATE ORDERS SET ORDER_DATE=NULL WHERE TRY_TO_DATE(ORDER_DATE)>CURRENT_DATE()',
           70,'MEDIUM',TRUE
    UNION ALL SELECT 'DUPLICATE_CUSTOMER_ID','DEDUP',
           'CREATE OR REPLACE TABLE CUSTOMERS AS SELECT * FROM CUSTOMERS QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY SOURCE_SYSTEM NULLS LAST)=1',
           90,'MEDIUM',TRUE
    UNION ALL SELECT 'DUPLICATE_ORDER_ID','DEDUP',
           'CREATE OR REPLACE TABLE ORDERS AS SELECT * FROM ORDERS QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ORDER_STATUS)=1',
           90,'MEDIUM',TRUE
    UNION ALL SELECT 'DUPLICATE_PRODUCT_ID','DEDUP',
           'CREATE OR REPLACE TABLE PRODUCTS AS SELECT * FROM PRODUCTS QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY ACTIVE_FLAG)=1',
           90,'MEDIUM',TRUE
    UNION ALL SELECT 'MISSING_CUSTOMER_ID','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL; DELETE FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL',
           60,'HIGH',TRUE
    UNION ALL SELECT 'MISSING_EMAIL','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL; DELETE FROM CUSTOMERS WHERE EMAIL IS NULL',
           55,'HIGH',TRUE
    UNION ALL SELECT 'INVALID_EMAIL','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$''); DELETE FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'')',
           55,'HIGH',TRUE
    UNION ALL SELECT 'MISSING_ORDER_CUSTOMER','QUARANTINE',
           'INSERT INTO ORDERS_QUARANTINE SELECT * FROM ORDERS WHERE CUSTOMER_ID IS NULL; DELETE FROM ORDERS WHERE CUSTOMER_ID IS NULL',
           60,'HIGH',TRUE
    UNION ALL SELECT 'ORPHAN_ORDER','QUARANTINE',
           'INSERT INTO ORDERS_QUARANTINE SELECT * FROM ORDERS o WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID); DELETE FROM ORDERS o WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID)',
           60,'HIGH',TRUE
) m ON i.ISSUE_TYPE = m.ISSUE_TYPE
WHERE i.STATUS = 'OPEN';

-- ---------------------------------------------------------------------
-- REMEDIATION AGENT (Cortex): narrate the recommended action for reviewers.
-- One concise sentence, action-oriented, references the method + risk.
-- ---------------------------------------------------------------------
UPDATE DQ_REMEDIATION_PLAN p
SET RECOMMENDED_ACTION = SNOWFLAKE.CORTEX.COMPLETE(
    'mistral-large2',
    CONCAT(
        'You are a data steward proposing a fix. In ONE short sentence, describe the ',
        'recommended remediation for a reviewer to approve. Be specific and calm. ',
        'Issue: ', p.ISSUE_TYPE, ' on table ', p.TABLE_NAME,
        ' | Fix method: ', p.FIX_METHOD,
        ' | Rows: ', p.AFFECTED_ROWS,
        ' | Risk: ', p.RISK_LEVEL, '. Do not include SQL.'
    )
)
WHERE RECOMMENDED_ACTION IS NULL;

-- Review the full plan (this is what Page 4 "Remediation Center" shows)
SELECT TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS, FIX_METHOD,
       CONFIDENCE, RISK_LEVEL, REQUIRES_APPROVAL, APPROVAL_STATUS,
       RECOMMENDED_ACTION
FROM DQ_REMEDIATION_PLAN
ORDER BY CASE FIX_METHOD WHEN 'QUARANTINE' THEN 1 WHEN 'DEDUP' THEN 2 ELSE 3 END,
         CONFIDENCE DESC;
