-- =====================================================================
-- GuardianAI | File 14c: VALIDATION AGENT for ALL 5 TABLES (volume-aware)
-- Re-runs detection for base 3 (file 04 logic) + new 2 (file 17 logic),
-- rescores with the 5-table volume-aware model (file 05c), snapshots AFTER,
-- and shows BEFORE vs AFTER. Use INSTEAD of 14 / 14b in the 5-table setup.
-- Run AFTER base remediation (13) and new-table remediation (19).
-- =====================================================================

USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE  GUARDIANAI_DB;
USE SCHEMA    CORE;

-- ---------------------------------------------------------------------
-- STEP 1: Re-detect everything into DQ_ISSUES.
-- ---------------------------------------------------------------------
TRUNCATE TABLE DQ_ISSUES;

-- ===== CUSTOMERS =====
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','MISSING_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS WHERE EMAIL IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','EMAIL','INVALID_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS
WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','DUPLICATE_CUSTOMER_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT CUSTOMER_ID,COUNT(*) cnt FROM CUSTOMERS WHERE CUSTOMER_ID IS NOT NULL GROUP BY CUSTOMER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','CUSTOMER_ID','MISSING_CUSTOMER_ID','CRITICAL',20,COUNT(*) FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','STATE','MISSING_STATE','LOW',3,COUNT(*) FROM CUSTOMERS WHERE STATE IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'CUSTOMERS','PHONE','INVALID_PHONE','MEDIUM',7,COUNT(*) FROM CUSTOMERS
WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE,'^[0-9]{10}$') HAVING COUNT(*)>0;

-- ===== ORDERS =====
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_DATE','FUTURE_ORDER_DATE','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_DATE(ORDER_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','MISSING_ORDER_CUSTOMER','HIGH',10,COUNT(*) FROM ORDERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','CUSTOMER_ID','ORPHAN_ORDER','CRITICAL',20,COUNT(*) FROM ORDERS o
WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_AMOUNT','NEGATIVE_ORDER_AMOUNT','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_NUMBER(ORDER_AMOUNT)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'ORDERS','ORDER_ID','DUPLICATE_ORDER_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT ORDER_ID,COUNT(*) cnt FROM ORDERS GROUP BY ORDER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;

-- ===== PRODUCTS =====
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','PRICE','NEGATIVE_PRICE','MEDIUM',7,COUNT(*) FROM PRODUCTS WHERE TRY_TO_NUMBER(PRICE)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','CATEGORY','MISSING_CATEGORY','LOW',3,COUNT(*) FROM PRODUCTS WHERE CATEGORY IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','PRODUCT_ID','DUPLICATE_PRODUCT_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT PRODUCT_ID,COUNT(*) cnt FROM PRODUCTS GROUP BY PRODUCT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PRODUCTS','ACTIVE_FLAG','INVALID_ACTIVE_FLAG','MEDIUM',7,COUNT(*) FROM PRODUCTS
WHERE ACTIVE_FLAG NOT IN ('Y','N') OR ACTIVE_FLAG IS NULL HAVING COUNT(*)>0;

-- ===== PAYMENTS (within + cross-table) =====
CREATE OR REPLACE TEMPORARY TABLE _ORD_AMT AS
SELECT ORDER_ID, MIN(TRY_TO_NUMBER(ORDER_AMOUNT)) AS ORDER_AMOUNT
FROM ORDERS WHERE ORDER_ID IS NOT NULL GROUP BY ORDER_ID;

INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_ID','DUPLICATE_PAYMENT_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT PAYMENT_ID,COUNT(*) cnt FROM PAYMENTS GROUP BY PAYMENT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','MISSING_ORDER_REF','HIGH',10,COUNT(*) FROM PAYMENTS WHERE ORDER_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','ORDER_ID','ORPHAN_PAYMENT','CRITICAL',20,COUNT(*) FROM PAYMENTS p
WHERE p.ORDER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','PAYMENT_AMOUNT_MISMATCH','HIGH',10,COUNT(*)
FROM PAYMENTS p JOIN _ORD_AMT o ON o.ORDER_ID=p.ORDER_ID
WHERE TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL AND o.ORDER_AMOUNT IS NOT NULL
  AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT))<>ABS(o.ORDER_AMOUNT) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_AMOUNT','NEGATIVE_PAYMENT_AMOUNT','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_NUMBER(PAYMENT_AMOUNT)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_DATE','FUTURE_PAYMENT_DATE','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_DATE(PAYMENT_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'PAYMENTS','PAYMENT_METHOD','INVALID_PAYMENT_METHOD','MEDIUM',7,COUNT(*) FROM PAYMENTS
WHERE PAYMENT_METHOD IS NULL OR PAYMENT_METHOD NOT IN ('CARD','UPI','NETBANKING','WALLET','COD') HAVING COUNT(*)>0;

-- ===== INVENTORY (within + cross-table) =====
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','INVENTORY_ID','DUPLICATE_INVENTORY_ID','CRITICAL',20,SUM(cnt) FROM
 (SELECT INVENTORY_ID,COUNT(*) cnt FROM INVENTORY GROUP BY INVENTORY_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','MISSING_PRODUCT_REF','HIGH',10,COUNT(*) FROM INVENTORY WHERE PRODUCT_ID IS NULL HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','PRODUCT_ID','ORPHAN_INVENTORY','CRITICAL',20,COUNT(*) FROM INVENTORY i
WHERE i.PRODUCT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID=i.PRODUCT_ID) HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','STOCK_QTY','NEGATIVE_STOCK','MEDIUM',7,COUNT(*) FROM INVENTORY WHERE TRY_TO_NUMBER(STOCK_QTY)<0 HAVING COUNT(*)>0;
INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
SELECT 'INVENTORY','WAREHOUSE','INVALID_WAREHOUSE','LOW',3,COUNT(*) FROM INVENTORY
WHERE WAREHOUSE IS NULL OR WAREHOUSE NOT IN ('WH-MUM','WH-DEL','WH-BLR','WH-KOL','WH-CHN','WH-HYD') HAVING COUNT(*)>0;

-- ---------------------------------------------------------------------
-- STEP 2: Recompute volume-aware scores for all 5 tables (file 05c model).
-- ---------------------------------------------------------------------
TRUNCATE TABLE DQ_HEALTH_SCORE;

INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
WITH table_stats AS (
    SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS TOTAL_ROWS FROM CUSTOMERS
    UNION ALL SELECT 'ORDERS',    COUNT(*) FROM ORDERS
    UNION ALL SELECT 'PRODUCTS',  COUNT(*) FROM PRODUCTS
    UNION ALL SELECT 'PAYMENTS',  COUNT(*) FROM PAYMENTS
    UNION ALL SELECT 'INVENTORY', COUNT(*) FROM INVENTORY
),
scored AS (
    SELECT i.TABLE_NAME,
        CASE i.SEVERITY WHEN 'CRITICAL' THEN 8 WHEN 'HIGH' THEN 4 WHEN 'MEDIUM' THEN 2 ELSE 1 END
        + CASE i.SEVERITY WHEN 'CRITICAL' THEN 1.5 WHEN 'HIGH' THEN 1.0 WHEN 'MEDIUM' THEN 0.7 ELSE 0.3 END
          * (100.0*i.AFFECTED_ROWS/NULLIF(s.TOTAL_ROWS,0)) AS ISSUE_PENALTY
    FROM DQ_ISSUES i JOIN table_stats s ON s.TABLE_NAME=i.TABLE_NAME
    WHERE i.STATUS='OPEN'
)
SELECT TABLE_NAME, ROUND(SUM(ISSUE_PENALTY),1),
    GREATEST(0,ROUND(100-SUM(ISSUE_PENALTY))),
    CASE WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=90 THEN 'LOW'
         WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=75 THEN 'MEDIUM'
         WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=50 THEN 'HIGH' ELSE 'CRITICAL' END
FROM scored GROUP BY TABLE_NAME;

INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
SELECT t.TABLE_NAME,0,100,'LOW'
FROM (SELECT 'CUSTOMERS' TABLE_NAME UNION ALL SELECT 'ORDERS' UNION ALL SELECT 'PRODUCTS'
      UNION ALL SELECT 'PAYMENTS' UNION ALL SELECT 'INVENTORY') t
WHERE t.TABLE_NAME NOT IN (SELECT TABLE_NAME FROM DQ_HEALTH_SCORE);

INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
SELECT 'OVERALL', ROUND(SUM(TOTAL_PENALTY),1), ROUND(AVG(HEALTH_SCORE)),
    CASE WHEN ROUND(AVG(HEALTH_SCORE))>=90 THEN 'LOW'
         WHEN ROUND(AVG(HEALTH_SCORE))>=75 THEN 'MEDIUM'
         WHEN ROUND(AVG(HEALTH_SCORE))>=50 THEN 'HIGH' ELSE 'CRITICAL' END
FROM DQ_HEALTH_SCORE WHERE TABLE_NAME<>'OVERALL';

-- ---------------------------------------------------------------------
-- STEP 3: AFTER snapshot + BEFORE/AFTER comparison (all 5 tables).
-- ---------------------------------------------------------------------
DELETE FROM DQ_HEALTH_HISTORY WHERE RUN_LABEL='AFTER_REMEDIATION';
INSERT INTO DQ_HEALTH_HISTORY (RUN_LABEL,TABLE_NAME,HEALTH_SCORE,BUSINESS_RISK)
SELECT 'AFTER_REMEDIATION',TABLE_NAME,HEALTH_SCORE,BUSINESS_RISK FROM DQ_HEALTH_SCORE;

SELECT
    COALESCE(b.TABLE_NAME,a.TABLE_NAME) AS table_name,
    b.HEALTH_SCORE AS before_score,
    a.HEALTH_SCORE AS after_score,
    a.HEALTH_SCORE - b.HEALTH_SCORE AS improvement,
    b.BUSINESS_RISK AS before_risk,
    a.BUSINESS_RISK AS after_risk
FROM      (SELECT * FROM DQ_HEALTH_HISTORY WHERE RUN_LABEL='BEFORE_REMEDIATION') b
FULL JOIN (SELECT * FROM DQ_HEALTH_HISTORY WHERE RUN_LABEL='AFTER_REMEDIATION')  a
       ON b.TABLE_NAME=a.TABLE_NAME
ORDER BY CASE WHEN COALESCE(b.TABLE_NAME,a.TABLE_NAME)='OVERALL' THEN 1 ELSE 0 END, table_name;
