-- =====================================================================
-- GuardianAI | File 14: ORCHESTRATION PROCEDURE BODIES
-- Real, runnable bodies for the procedures the DAG calls.
-- =====================================================================
USE WAREHOUSE GUARDIANAI_WH;
USE DATABASE GUARDIANAI_DB;
USE SCHEMA CORE;
-- ---------------------------------------------------------------------
-- SP_DETECT_BASE : Observer Agent for CUSTOMERS/ORDERS/PRODUCTS (file 04)
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DETECT_BASE()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','EMAIL','MISSING_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS WHERE EMAIL IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','EMAIL','INVALID_EMAIL','HIGH',10,COUNT(*) FROM CUSTOMERS
   WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','CUSTOMER_ID','DUPLICATE_CUSTOMER_ID','CRITICAL',20,SUM(cnt) FROM
   (SELECT CUSTOMER_ID,COUNT(*) cnt FROM CUSTOMERS WHERE CUSTOMER_ID IS NOT NULL GROUP BY CUSTOMER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','CUSTOMER_ID','MISSING_CUSTOMER_ID','CRITICAL',20,COUNT(*) FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','STATE','MISSING_STATE','LOW',3,COUNT(*) FROM CUSTOMERS WHERE STATE IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'CUSTOMERS','PHONE','INVALID_PHONE','MEDIUM',7,COUNT(*) FROM CUSTOMERS
   WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE,'^[0-9]{10}$') HAVING COUNT(*)>0;

  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'ORDERS','ORDER_DATE','FUTURE_ORDER_DATE','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_DATE(ORDER_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'ORDERS','CUSTOMER_ID','MISSING_ORDER_CUSTOMER','HIGH',10,COUNT(*) FROM ORDERS WHERE CUSTOMER_ID IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'ORDERS','CUSTOMER_ID','ORPHAN_ORDER','CRITICAL',20,COUNT(*) FROM ORDERS o
   WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID) HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'ORDERS','ORDER_AMOUNT','NEGATIVE_ORDER_AMOUNT','MEDIUM',7,COUNT(*) FROM ORDERS WHERE TRY_TO_NUMBER(ORDER_AMOUNT)<0 HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'ORDERS','ORDER_ID','DUPLICATE_ORDER_ID','CRITICAL',20,SUM(cnt) FROM
   (SELECT ORDER_ID,COUNT(*) cnt FROM ORDERS GROUP BY ORDER_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;

  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PRODUCTS','PRICE','NEGATIVE_PRICE','MEDIUM',7,COUNT(*) FROM PRODUCTS WHERE TRY_TO_NUMBER(PRICE)<0 HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PRODUCTS','CATEGORY','MISSING_CATEGORY','LOW',3,COUNT(*) FROM PRODUCTS WHERE CATEGORY IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PRODUCTS','PRODUCT_ID','DUPLICATE_PRODUCT_ID','CRITICAL',20,SUM(cnt) FROM
   (SELECT PRODUCT_ID,COUNT(*) cnt FROM PRODUCTS GROUP BY PRODUCT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PRODUCTS','ACTIVE_FLAG','INVALID_ACTIVE_FLAG','MEDIUM',7,COUNT(*) FROM PRODUCTS
   WHERE ACTIVE_FLAG NOT IN ('Y','N') OR ACTIVE_FLAG IS NULL HAVING COUNT(*)>0;
  RETURN 'detect base complete';
END;
$$;
-- ---------------------------------------------------------------------
    -- SP_DETECT_NEW : Observer Agent for PAYMENTS + INVENTORY (file 17)
    -- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DETECT_NEW()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE _ORD_AMT AS
    SELECT ORDER_ID, MIN(TRY_TO_NUMBER(ORDER_AMOUNT)) AS ORDER_AMOUNT
    FROM ORDERS WHERE ORDER_ID IS NOT NULL GROUP BY ORDER_ID;

  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','PAYMENT_ID','DUPLICATE_PAYMENT_ID','CRITICAL',20,SUM(cnt) FROM
   (SELECT PAYMENT_ID,COUNT(*) cnt FROM PAYMENTS GROUP BY PAYMENT_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','ORDER_ID','MISSING_ORDER_REF','HIGH',10,COUNT(*) FROM PAYMENTS WHERE ORDER_ID IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','ORDER_ID','ORPHAN_PAYMENT','CRITICAL',20,COUNT(*) FROM PAYMENTS p
   WHERE p.ORDER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID) HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','PAYMENT_AMOUNT','PAYMENT_AMOUNT_MISMATCH','HIGH',10,COUNT(*)
   FROM PAYMENTS p JOIN _ORD_AMT o ON o.ORDER_ID=p.ORDER_ID
   WHERE TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL AND o.ORDER_AMOUNT IS NOT NULL
     AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT))<>ABS(o.ORDER_AMOUNT) HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','PAYMENT_AMOUNT','NEGATIVE_PAYMENT_AMOUNT','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_NUMBER(PAYMENT_AMOUNT)<0 HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','PAYMENT_DATE','FUTURE_PAYMENT_DATE','MEDIUM',7,COUNT(*) FROM PAYMENTS WHERE TRY_TO_DATE(PAYMENT_DATE)>CURRENT_DATE() HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'PAYMENTS','PAYMENT_METHOD','INVALID_PAYMENT_METHOD','MEDIUM',7,COUNT(*) FROM PAYMENTS
   WHERE PAYMENT_METHOD IS NULL OR PAYMENT_METHOD NOT IN ('CARD','UPI','NETBANKING','WALLET','COD') HAVING COUNT(*)>0;

  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'INVENTORY','INVENTORY_ID','DUPLICATE_INVENTORY_ID','CRITICAL',20,SUM(cnt) FROM
   (SELECT INVENTORY_ID,COUNT(*) cnt FROM INVENTORY GROUP BY INVENTORY_ID HAVING COUNT(*)>1) d HAVING SUM(cnt)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'INVENTORY','PRODUCT_ID','MISSING_PRODUCT_REF','HIGH',10,COUNT(*) FROM INVENTORY WHERE PRODUCT_ID IS NULL HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'INVENTORY','PRODUCT_ID','ORPHAN_INVENTORY','CRITICAL',20,COUNT(*) FROM INVENTORY i
   WHERE i.PRODUCT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID=i.PRODUCT_ID) HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'INVENTORY','STOCK_QTY','NEGATIVE_STOCK','MEDIUM',7,COUNT(*) FROM INVENTORY WHERE TRY_TO_NUMBER(STOCK_QTY)<0 HAVING COUNT(*)>0;
  INSERT INTO DQ_ISSUES (TABLE_NAME,COLUMN_NAME,ISSUE_TYPE,SEVERITY,PENALTY,AFFECTED_ROWS)
  SELECT 'INVENTORY','WAREHOUSE','INVALID_WAREHOUSE','LOW',3,COUNT(*) FROM INVENTORY
   WHERE WAREHOUSE IS NULL OR WAREHOUSE NOT IN ('WH-MUM','WH-DEL','WH-BLR','WH-KOL','WH-CHN','WH-HYD') HAVING COUNT(*)>0;
  RETURN 'detect new complete';
END;
$$;
-- ---------------------------------------------------------------------
    -- SP_SCORE_5TABLES : volume-aware scoring (file 05c)
    -- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_SCORE_5TABLES()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  TRUNCATE TABLE DQ_HEALTH_SCORE;
  INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
  WITH table_stats AS (
      SELECT 'CUSTOMERS' TABLE_NAME, COUNT(*) TOTAL_ROWS FROM CUSTOMERS
      UNION ALL SELECT 'ORDERS',COUNT(*) FROM ORDERS
      UNION ALL SELECT 'PRODUCTS',COUNT(*) FROM PRODUCTS
      UNION ALL SELECT 'PAYMENTS',COUNT(*) FROM PAYMENTS
      UNION ALL SELECT 'INVENTORY',COUNT(*) FROM INVENTORY),
  scored AS (
      SELECT i.TABLE_NAME,
        CASE i.SEVERITY WHEN 'CRITICAL' THEN 8 WHEN 'HIGH' THEN 4 WHEN 'MEDIUM' THEN 2 ELSE 1 END
        + CASE i.SEVERITY WHEN 'CRITICAL' THEN 1.5 WHEN 'HIGH' THEN 1.0 WHEN 'MEDIUM' THEN 0.7 ELSE 0.3 END
          * (100.0*i.AFFECTED_ROWS/NULLIF(s.TOTAL_ROWS,0)) AS ISSUE_PENALTY
      FROM DQ_ISSUES i JOIN table_stats s ON s.TABLE_NAME=i.TABLE_NAME WHERE i.STATUS='OPEN')
  SELECT TABLE_NAME, ROUND(SUM(ISSUE_PENALTY),1), GREATEST(0,ROUND(100-SUM(ISSUE_PENALTY))),
      CASE WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=90 THEN 'LOW'
           WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=75 THEN 'MEDIUM'
           WHEN GREATEST(0,100-SUM(ISSUE_PENALTY))>=50 THEN 'HIGH' ELSE 'CRITICAL' END
  FROM scored GROUP BY TABLE_NAME;

  INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
  SELECT t.TABLE_NAME,0,100,'LOW' FROM
   (SELECT 'CUSTOMERS' TABLE_NAME UNION ALL SELECT 'ORDERS' UNION ALL SELECT 'PRODUCTS'
    UNION ALL SELECT 'PAYMENTS' UNION ALL SELECT 'INVENTORY') t
  WHERE t.TABLE_NAME NOT IN (SELECT TABLE_NAME FROM DQ_HEALTH_SCORE);

  INSERT INTO DQ_HEALTH_SCORE (TABLE_NAME,TOTAL_PENALTY,HEALTH_SCORE,BUSINESS_RISK)
  SELECT 'OVERALL', ROUND(SUM(TOTAL_PENALTY),1), ROUND(AVG(HEALTH_SCORE)),
      CASE WHEN ROUND(AVG(HEALTH_SCORE))>=90 THEN 'LOW'
           WHEN ROUND(AVG(HEALTH_SCORE))>=75 THEN 'MEDIUM'
           WHEN ROUND(AVG(HEALTH_SCORE))>=50 THEN 'HIGH' ELSE 'CRITICAL' END
  FROM DQ_HEALTH_SCORE WHERE TABLE_NAME<>'OVERALL';
  RETURN 'score complete';
END;
$$;
-- ---------------------------------------------------------------------
    -- SP_DIAGNOSE / SP_IMPACT / SP_EXEC_SUMMARY : Cortex agents (07-09)
    -- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_DIAGNOSE()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  TRUNCATE TABLE DQ_ISSUE_ANALYSIS;
  INSERT INTO DQ_ISSUE_ANALYSIS (ISSUE_ID,TABLE_NAME,ISSUE_TYPE,SEVERITY,AFFECTED_ROWS)
  SELECT ISSUE_ID,TABLE_NAME,ISSUE_TYPE,SEVERITY,AFFECTED_ROWS FROM DQ_ISSUES WHERE STATUS='OPEN';
  UPDATE DQ_ISSUE_ANALYSIS a
  SET ROOT_CAUSE = SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
    CONCAT('You are a senior data quality engineer. In 1-2 short sentences explain the most likely ROOT CAUSE. ',
           'Be specific and technical. Do not restate the issue. Do not give a fix. ',
           'Table: ',a.TABLE_NAME,' | Issue: ',a.ISSUE_TYPE,' | Severity: ',a.SEVERITY,' | Rows: ',a.AFFECTED_ROWS,'.'))
  WHERE a.ROOT_CAUSE IS NULL;
  RETURN 'diagnose complete';
END;
$$;
CREATE OR REPLACE PROCEDURE SP_IMPACT()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  UPDATE DQ_ISSUE_ANALYSIS a
  SET BUSINESS_IMPACT = SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
    CONCAT('You are a data governance lead briefing executives. In 2 short sentences explain the BUSINESS IMPACT ',
           'in plain language (revenue, compliance, trust, reporting). No jargon. No fix. ',
           'Table: ',a.TABLE_NAME,' | Issue: ',a.ISSUE_TYPE,' | Severity: ',a.SEVERITY,
           ' | Rows: ',a.AFFECTED_ROWS,' | Root cause: ',COALESCE(a.ROOT_CAUSE,'n/a'),'.'))
  WHERE a.BUSINESS_IMPACT IS NULL;
  UPDATE DQ_ISSUE_ANALYSIS SET IMPACT_LEVEL=
    CASE SEVERITY WHEN 'CRITICAL' THEN 'HIGH' WHEN 'HIGH' THEN 'HIGH' WHEN 'MEDIUM' THEN 'MEDIUM' ELSE 'LOW' END
  WHERE IMPACT_LEVEL IS NULL;
  RETURN 'impact complete';
END;
$$;
CREATE OR REPLACE PROCEDURE SP_EXEC_SUMMARY()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
  INSERT INTO DQ_EXEC_SUMMARY (SUMMARY_TEXT)
  SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
    CONCAT('You are a CDO writing a 3-sentence executive briefing on enterprise data quality. Direct and calm. ',
           'State overall trust score, biggest risks, recommended priority. No bullet points. Facts: ',
           'Overall score: ',(SELECT HEALTH_SCORE FROM DQ_HEALTH_SCORE WHERE TABLE_NAME='OVERALL'),'/100. ',
           'Open issues: ',(SELECT COUNT(*) FROM DQ_ISSUES WHERE STATUS='OPEN'),'. ',
           'Critical: ',(SELECT COUNT(*) FROM DQ_ISSUES WHERE STATUS='OPEN' AND SEVERITY='CRITICAL'),'. ',
           'Worst tables: ',(SELECT LISTAGG(TABLE_NAME||' ('||HEALTH_SCORE||')',', ')
                             FROM DQ_HEALTH_SCORE WHERE TABLE_NAME<>'OVERALL'),'.'));
  RETURN 'exec summary complete';
END;
$$;
CREATE OR REPLACE PROCEDURE SP_REBUILD_PLAN()
    RETURNS STRING
    LANGUAGE SQL
    AS $$
BEGIN
    -- Rebuild from scratch each cycle so the plan matches current issues.
    TRUNCATE TABLE DQ_REMEDIATION_PLAN;

INSERT INTO DQ_REMEDIATION_PLAN
    (ISSUE_ID, TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS,
     FIX_METHOD, FIX_SQL, CONFIDENCE, RISK_LEVEL, REQUIRES_APPROVAL)
SELECT
    i.ISSUE_ID, i.TABLE_NAME, i.ISSUE_TYPE, i.SEVERITY, i.AFFECTED_ROWS,
    m.FIX_METHOD, m.FIX_SQL, m.CONFIDENCE, m.RISK_LEVEL, m.REQUIRES_APPROVAL
FROM DQ_ISSUES i
JOIN (
    SELECT 'MISSING_STATE' AS ISSUE_TYPE, 'AUTO_FIX' AS FIX_METHOD,
           'UPDATE CUSTOMERS SET STATE=''UNKNOWN'' WHERE STATE IS NULL' AS FIX_SQL,
           95 AS CONFIDENCE, 'LOW' AS RISK_LEVEL, FALSE AS REQUIRES_APPROVAL
    UNION ALL SELECT 'INVALID_PHONE','AUTO_FIX',
           'UPDATE CUSTOMERS SET PHONE=NULL WHERE PHONE IS NOT NULL AND NOT REGEXP_LIKE(PHONE,''^[0-9]{10}$'')',
           90,'LOW',FALSE
    UNION ALL SELECT 'MISSING_CATEGORY','AUTO_FIX',
           'UPDATE PRODUCTS SET CATEGORY=''UNCATEGORIZED'' WHERE CATEGORY IS NULL',
           95,'LOW',FALSE
    UNION ALL SELECT 'INVALID_ACTIVE_FLAG','AUTO_FIX',
           'UPDATE PRODUCTS SET ACTIVE_FLAG=''N'' WHERE ACTIVE_FLAG NOT IN (''Y'',''N'') OR ACTIVE_FLAG IS NULL',
           85,'MEDIUM',FALSE
    UNION ALL SELECT 'NEGATIVE_PRICE','AUTO_FIX',
           'UPDATE PRODUCTS SET PRICE=ABS(TRY_TO_NUMBER(PRICE)) WHERE TRY_TO_NUMBER(PRICE)<0',
           80,'MEDIUM',FALSE
    UNION ALL SELECT 'NEGATIVE_ORDER_AMOUNT','AUTO_FIX',
           'UPDATE ORDERS SET ORDER_AMOUNT=ABS(TRY_TO_NUMBER(ORDER_AMOUNT)) WHERE TRY_TO_NUMBER(ORDER_AMOUNT)<0',
           80,'MEDIUM',FALSE
    UNION ALL SELECT 'FUTURE_ORDER_DATE','AUTO_FIX',
           'UPDATE ORDERS SET ORDER_DATE=NULL WHERE TRY_TO_DATE(ORDER_DATE)>CURRENT_DATE()',
           70,'MEDIUM',FALSE
    UNION ALL SELECT 'DUPLICATE_CUSTOMER_ID','DEDUP',
           'CREATE OR REPLACE TEMPORARY TABLE _KEEP_CUST AS ' ||
            'SELECT * FROM CUSTOMERS QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY SOURCE_SYSTEM NULLS LAST)=1 OR CUSTOMER_ID IS NULL; ' ||
            'TRUNCATE TABLE CUSTOMERS; ' ||
            'INSERT INTO CUSTOMERS SELECT * FROM _KEEP_CUST',
           90,'MEDIUM',FALSE
    UNION ALL SELECT 'DUPLICATE_ORDER_ID','DEDUP',
           'CREATE OR REPLACE TEMPORARY TABLE _KEEP_ORD AS ' ||
            'SELECT * FROM ORDERS QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ORDER_STATUS)=1; ' ||
            'TRUNCATE TABLE ORDERS; ' ||
            'INSERT INTO ORDERS SELECT * FROM _KEEP_ORD',
           90,'MEDIUM',FALSE
    UNION ALL SELECT 'DUPLICATE_PRODUCT_ID','DEDUP',
           'CREATE OR REPLACE TEMPORARY TABLE _KEEP_PROD AS ' ||
            'SELECT * FROM PRODUCTS QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY ACTIVE_FLAG)=1; ' ||
            'TRUNCATE TABLE PRODUCTS; ' ||
            'INSERT INTO PRODUCTS SELECT * FROM _KEEP_PROD',
           90,'MEDIUM',FALSE
    UNION ALL SELECT 'MISSING_CUSTOMER_ID','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL; DELETE FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL',
           60,'HIGH',FALSE
    UNION ALL SELECT 'MISSING_EMAIL','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE EMAIL IS NULL; DELETE FROM CUSTOMERS WHERE EMAIL IS NULL',
           55,'HIGH',FALSE
    UNION ALL SELECT 'INVALID_EMAIL','QUARANTINE',
           'INSERT INTO CUSTOMERS_QUARANTINE SELECT * FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$''); DELETE FROM CUSTOMERS WHERE EMAIL IS NOT NULL AND NOT REGEXP_LIKE(EMAIL,''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'')',
           55,'HIGH',FALSE
    UNION ALL SELECT 'MISSING_ORDER_CUSTOMER','QUARANTINE',
           'INSERT INTO ORDERS_QUARANTINE SELECT * FROM ORDERS WHERE CUSTOMER_ID IS NULL; DELETE FROM ORDERS WHERE CUSTOMER_ID IS NULL',
           60,'HIGH',FALSE
    UNION ALL SELECT 'ORPHAN_ORDER','QUARANTINE',
           'INSERT INTO ORDERS_QUARANTINE SELECT * FROM ORDERS o WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID); DELETE FROM ORDERS o WHERE o.CUSTOMER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM CUSTOMERS c WHERE c.CUSTOMER_ID=o.CUSTOMER_ID)',
           60,'HIGH',FALSE
) m ON i.ISSUE_TYPE = m.ISSUE_TYPE
WHERE i.STATUS = 'OPEN';


-- Idempotent: clear any previous new-table plan rows before re-inserting
DELETE FROM DQ_REMEDIATION_PLAN WHERE TABLE_NAME IN ('PAYMENTS','INVENTORY');

INSERT INTO DQ_REMEDIATION_PLAN
    (ISSUE_ID, TABLE_NAME, ISSUE_TYPE, SEVERITY, AFFECTED_ROWS,
     FIX_METHOD, FIX_SQL, CONFIDENCE, RISK_LEVEL, REQUIRES_APPROVAL)
SELECT
    i.ISSUE_ID, i.TABLE_NAME, i.ISSUE_TYPE, i.SEVERITY, i.AFFECTED_ROWS,
    m.FIX_METHOD, m.FIX_SQL, m.CONFIDENCE, m.RISK_LEVEL, m.REQUIRES_APPROVAL
FROM DQ_ISSUES i
JOIN (
    -- ---------------- PAYMENTS ----------------
    SELECT 'DUPLICATE_PAYMENT_ID' AS ISSUE_TYPE, 'DEDUP' AS FIX_METHOD,
        'CREATE OR REPLACE TEMPORARY TABLE _KEEP_PAY AS ' ||
            'SELECT * FROM PAYMENTS QUALIFY ROW_NUMBER() OVER (PARTITION BY PAYMENT_ID ORDER BY PAYMENT_STATUS)=1; ' ||
            'TRUNCATE TABLE PAYMENTS; ' ||
            'INSERT INTO PAYMENTS SELECT * FROM _KEEP_PAY' AS FIX_SQL,
        90 AS CONFIDENCE, 'MEDIUM' AS RISK_LEVEL, TRUE AS REQUIRES_APPROVAL
    UNION ALL SELECT 'MISSING_ORDER_REF','QUARANTINE',
        'INSERT INTO PAYMENTS_QUARANTINE SELECT * FROM PAYMENTS WHERE ORDER_ID IS NULL; DELETE FROM PAYMENTS WHERE ORDER_ID IS NULL',
        60,'HIGH',TRUE
    UNION ALL SELECT 'ORPHAN_PAYMENT','QUARANTINE',
        'INSERT INTO PAYMENTS_QUARANTINE SELECT * FROM PAYMENTS p WHERE p.ORDER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID); DELETE FROM PAYMENTS p WHERE p.ORDER_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID)',
        60,'HIGH',TRUE
    UNION ALL SELECT 'PAYMENT_AMOUNT_MISMATCH','QUARANTINE',
        'INSERT INTO PAYMENTS_QUARANTINE SELECT p.* FROM PAYMENTS p WHERE EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID AND TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL AND TRY_TO_NUMBER(o.ORDER_AMOUNT) IS NOT NULL AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT))<>ABS(TRY_TO_NUMBER(o.ORDER_AMOUNT))); DELETE FROM PAYMENTS p WHERE EXISTS (SELECT 1 FROM ORDERS o WHERE o.ORDER_ID=p.ORDER_ID AND TRY_TO_NUMBER(p.PAYMENT_AMOUNT) IS NOT NULL AND TRY_TO_NUMBER(o.ORDER_AMOUNT) IS NOT NULL AND ABS(TRY_TO_NUMBER(p.PAYMENT_AMOUNT))<>ABS(TRY_TO_NUMBER(o.ORDER_AMOUNT)))',
        55,'HIGH',TRUE
    UNION ALL SELECT 'NEGATIVE_PAYMENT_AMOUNT','AUTO_FIX',
        'UPDATE PAYMENTS SET PAYMENT_AMOUNT=ABS(TRY_TO_NUMBER(PAYMENT_AMOUNT)) WHERE TRY_TO_NUMBER(PAYMENT_AMOUNT)<0',
        80,'MEDIUM',TRUE
    UNION ALL SELECT 'FUTURE_PAYMENT_DATE','AUTO_FIX',
        'UPDATE PAYMENTS SET PAYMENT_DATE=NULL WHERE TRY_TO_DATE(PAYMENT_DATE)>CURRENT_DATE()',
        70,'MEDIUM',TRUE
    UNION ALL SELECT 'INVALID_PAYMENT_METHOD','AUTO_FIX',
        'UPDATE PAYMENTS SET PAYMENT_METHOD=''CARD'' WHERE PAYMENT_METHOD IS NULL OR PAYMENT_METHOD NOT IN (''CARD'',''UPI'',''NETBANKING'',''WALLET'',''COD'')',
        65,'MEDIUM',TRUE
    -- ---------------- INVENTORY ----------------
    UNION ALL SELECT 'DUPLICATE_INVENTORY_ID','DEDUP',
        'CREATE OR REPLACE TEMPORARY TABLE _KEEP_INV AS ' ||
            'SELECT * FROM INVENTORY QUALIFY ROW_NUMBER() OVER (PARTITION BY INVENTORY_ID ORDER BY WAREHOUSE)=1; ' ||
            'TRUNCATE TABLE INVENTORY; ' ||
            'INSERT INTO INVENTORY SELECT * FROM _KEEP_INV',
        90,'MEDIUM',TRUE
    UNION ALL SELECT 'MISSING_PRODUCT_REF','QUARANTINE',
        'INSERT INTO INVENTORY_QUARANTINE SELECT * FROM INVENTORY WHERE PRODUCT_ID IS NULL; DELETE FROM INVENTORY WHERE PRODUCT_ID IS NULL',
        60,'HIGH',TRUE
    UNION ALL SELECT 'ORPHAN_INVENTORY','QUARANTINE',
        'INSERT INTO INVENTORY_QUARANTINE SELECT * FROM INVENTORY i WHERE i.PRODUCT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID=i.PRODUCT_ID); DELETE FROM INVENTORY i WHERE i.PRODUCT_ID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID=i.PRODUCT_ID)',
        60,'HIGH',TRUE
    UNION ALL SELECT 'NEGATIVE_STOCK','AUTO_FIX',
        'UPDATE INVENTORY SET STOCK_QTY=0 WHERE TRY_TO_NUMBER(STOCK_QTY)<0',
        85,'MEDIUM',TRUE
    UNION ALL SELECT 'INVALID_WAREHOUSE','AUTO_FIX',
        'UPDATE INVENTORY SET WAREHOUSE=''WH-MUM'' WHERE WAREHOUSE IS NULL OR WAREHOUSE NOT IN (''WH-MUM'',''WH-DEL'',''WH-BLR'',''WH-KOL'',''WH-CHN'',''WH-HYD'')',
        65,'LOW',FALSE
) m ON i.ISSUE_TYPE = m.ISSUE_TYPE
WHERE i.STATUS = 'OPEN' AND i.TABLE_NAME IN ('PAYMENTS','INVENTORY');

    -- AI-narrated recommendation for the reviewer (one sentence each)
    UPDATE DQ_REMEDIATION_PLAN p
    SET RECOMMENDED_ACTION = SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
        CONCAT('You are a data steward proposing a fix. In ONE short sentence, describe the ',
               'recommended remediation for a reviewer to approve. Be specific and calm. ',
               'Issue: ', p.ISSUE_TYPE, ' on table ', p.TABLE_NAME,
               ' | Fix method: ', p.FIX_METHOD, ' | Rows: ', p.AFFECTED_ROWS,
               ' | Risk: ', p.RISK_LEVEL, '. Do not include SQL.'))
    WHERE p.RECOMMENDED_ACTION IS NULL;

    RETURN 'remediation plan rebuilt for all 5 tables';
END;
$$;
SELECT
    'Orchestration procedure bodies created' AS status;